const state={history:[],current:'start'};
const card=document.getElementById('card');
const breadcrumb=document.getElementById('breadcrumb');
const backBtn=document.getElementById('backBtn');
const restartBtn=document.getElementById('restartBtn');
const objectionBtn=document.getElementById('objectionBtn');

function go(next,label){state.history.push(state.current);state.current=next;render(label)}
function restart(){state.history=[];state.current='start';render()}
function back(){if(!state.history.length)return;state.current=state.history.pop();render()}
function btn(text,next){return `<button class="choice" onclick="go('${next}')">${text}</button>`}

const screens={
start:()=>`<span class="tag">Старт дзвінка</span><h2>Привітання</h2><div class="script">Добрий день, <b>[Ім’я]</b>! Це <b>[ім’я менеджера]</b>, АнтиШкола. Зручно зараз кілька хвилин поспілкуватися про ваше навчання?</div><div class="grid">${btn('Так, зручно','goal')}${btn('Ні, незручно','callback')}</div>`,
callback:()=>`<span class="tag">Домовленість</span><h2>Переносимо розмову</h2><div class="script">Розумію. Підкажіть, будь ласка, коли вам буде зручно, щоб я набрала?</div><div class="hint">Зафіксуйте конкретний день і час.</div>${btn('Домовились про час','finish')}`,
goal:()=>`<span class="tag">Результат і ціль</span><h2>Повертаємось до старту</h2><p>Порівнюємо не лише відчуття студента, а весь шлях навчання.</p><div class="steps"><div class="step"><b>🎯 Ціль на старті</b><br>Що студент хотів отримати від навчання?</div><div class="step"><b>📝 Фідбек із пробного</b><br>Які труднощі, рівень і сильні сторони були зафіксовані на старті?</div><div class="step"><b>📈 Поточний фідбек викладача</b><br>Що вже змінилося, що виходить краще, над чим ще працювати?</div></div><div class="script">На старті вашою ціллю було <b>[ціль]</b>. На пробному ми фіксували, що було складно з <b>[навичка]</b>. Зараз викладач відзначає <b>[конкретний прогрес]</b>. Як ви самі оцінюєте результат?</div><div class="grid">${btn('✅ Ціль досягнута','scenario1')}${btn('⏳ Ціль ще не досягнута','scenario2')}${btn('😕 Щось у процесі не підійшло','scenario3')}${btn('⭐ Ціль досягнута, продовжувати не планує','scenario4')}</div><div class="mini">Якщо студент каже «не бачу прогресу» — використайте окрему гілку аудиту.</div>${btn('Студент не бачить прогресу','audit')}`,
audit:()=>`<span class="tag">Не бачить прогресу</span><h2>Показуємо зміни через факти</h2><div class="script">На пробному уроці ми фіксували, що вам було складно з <b>[тема/навичка]</b>. Зараз викладач відзначає, що <b>[конкретний прогрес]</b>. Тобто зміни вже є, навіть якщо в процесі вони не завжди так помітні.</div><div class="script">Щоб оцінити результат не лише за відчуттями, можемо пройти аудит знань. Так буде видно, що вже добре засвоєно, а над чим ще варто попрацювати.</div><div class="grid">${btn('Погоджується на аудит','afterAudit')}${btn('Не хоче аудит','continueQ')}</div>`,
afterAudit:()=>`<span class="tag">Аудит</span><h2>Фіксуємо наступний крок</h2><div class="success">Домовляємось про аудит → після результату визначаємо наступний крок у навчанні.</div>${btn('Перейти до рішення про продовження','continueQ')}`,
scenario1:()=>`<span class="tag">Сценарій 1</span><h2>Ціль досягнута</h2><div class="script">Супер, дуже рада це чути 💙 Першу ціль ми з вами підкорили. Саме час визначити наступну — підкажіть, яка це буде?</div><div class="script">Я також поспілкувалась із викладачем. Він/вона відзначає, що у вас добре виходить <b>[досягнення]</b>, і водночас варто ще попрацювати над <b>[зона росту]</b>.</div>${btn('Далі','continueQ')}`,
scenario2:()=>`<span class="tag">Сценарій 2</span><h2>Ціль ще не досягнута</h2><div class="script">Так, погоджуюсь, для такої цілі потрібно трохи більше часу.</div><div class="script">На пробному ми фіксували <b>[стартова складність]</b>, а зараз викладач уже бачить <b>[конкретний прогрес]</b>. Наступна зона росту — <b>[що далі]</b>.</div><div class="hint">Якщо студент не відчуває прогресу — запропонуйте аудит знань.</div><div class="grid">${btn('Студент бачить прогрес','continueQ')}${btn('Не бачить прогресу','audit')}</div>`,
scenario3:()=>`<span class="tag">Сценарій 3</span><h2>Щось не підійшло</h2><div class="script">Підкажіть, будь ласка, чого саме не вистачило або що хотілося б змінити?</div><div class="script">Дякую, зрозуміла вас. Якщо ми врахуємо ці побажання та внесемо зміни, ви будете готові продовжити навчання?</div><div class="grid">${btn('Так','package')}${btn('Ні / сумнівається','objections')}</div>`,
scenario4:()=>`<span class="tag">Сценарій 4</span><h2>Ціль досягнута, продовжувати не планує</h2><div class="script">Класно, що ви отримали бажаний результат 💙 А як плануєте підтримувати рівень далі?</div><div class="script">Якщо активної розмовної практики буде мало, навичка поступово слабшатиме. Можемо підібрати легший формат без великого навантаження — лише для підтримки рівня.</div><div class="grid">${btn('Цікавить легший формат','package')}${btn('Не цікавить','objections')}</div>`,
continueQ:()=>`<span class="tag">Рішення</span><h2>Чи планує студент продовжувати?</h2><div class="script">З огляду на ваш результат і те, над чим ще плануємо працювати, скажіть, будь ласка, ви плануєте продовжувати навчання?</div><div class="grid">${btn('💚 Так','package')}${btn('💛 Сумнівається / не знає','objections')}${btn('❤️ Ні','objections')}</div>`,
package:()=>`<span class="tag">Рекомендація</span><h2>Підбираємо оптимальний варіант</h2><p>Не перелічуємо всі продукти. Даємо одну рекомендацію під конкретну ціль і ситуацію.</p><div class="script">З огляду на вашу ціль, прогрес і рекомендацію викладача, оптимально буде <b>[формат / пакет]</b>, тому що <b>[чому саме]</b>. Як вам такий варіант? Зупиняємось на ньому?</div><div class="grid">${btn('Так','agreement')}${btn('Є сумнів','objections')}</div>`,
objections:()=>`<span class="tag">Заперечення</span><h2>Не сперечаємось — знаходимо реальну причину</h2><div class="steps"><div class="step"><b>1. Причина</b> — що реально зупиняє?</div><div class="step"><b>2. Перевірка</b> — це єдина причина?</div><div class="step"><b>3. Можливості</b> — час / бюджет / формат / інтенсивність.</div><div class="step"><b>4. Одне рішення</b> — лише релевантний варіант.</div><div class="step"><b>5. Перевірка</b> — чи вирішує це питання?</div></div><div class="grid">${btn('⏰ Немає часу','objTime')}${btn('💳 Фінанси','objMoney')}${btn('💡 Відключення світла','objPower')}${btn('💬 Інша причина','objOther')}</div>`,
objTime:()=>`<span class="tag">Немає часу</span><h2>Шукаємо реальну місткість у графіку</h2><div class="script">Розумію. Скажіть, будь ласка, це єдина причина, яка зараз зупиняє від продовження?</div><div class="script">Яка зайнятість щодо мови зараз була б для вас реально комфортною?</div><div class="hint">Після відповіді запропонуйте ОДИН формат, який відповідає цій можливості.</div>${btn('Перевірити готовність','agreement')}`,
objMoney:()=>`<span class="tag">Фінанси</span><h2>Уточнюємо бюджет, а не вгадуємо</h2><div class="script">Якщо відкинути фінансову складову, решта у нашому навчанні вам підходить?</div><div class="script">Підкажіть, а яку суму були б зараз готові заплатити за навчання?</div><div class="hint">Після відповіді: один релевантний варіант оплати / пакета.</div>${btn('Перевірити готовність','agreement')}`,
objPower:()=>`<span class="tag">Світло / зв’язок</span><h2>Уточнюємо, де саме проблема</h2><div class="script">Розумію. Підкажіть, будь ласка, що найбільше заважає: нестабільний графік, пропуски занять чи інтернет?</div><div class="hint">Підлаштуйте рішення під конкретну проблему: час, перенесення, стабільні години, формат.</div>${btn('Перевірити готовність','agreement')}`,
objOther:()=>`<span class="tag">Інше заперечення</span><h2>Універсальний маршрут</h2><div class="script">Що зараз найбільше зупиняє вас від продовження?</div><div class="script">Якщо вирішити саме це питання, ви були б готові продовжити?</div><div class="hint">З’ясуйте можливості → дайте одне рішення → перевірте реакцію.</div>${btn('Перейти до домовленості','agreement')}`,
agreement:()=>`<span class="tag">Фінал</span><h2>Фіксуємо домовленість</h2><div class="steps"><div class="step"><b>Готовий оплачувати</b> → пакет + посилання + дата оплати.</div><div class="step"><b>Потрібно подумати</b> → скільки часу + точна дата повернення.</div><div class="step"><b>Потрібні зміни</b> → що змінюємо + коли повертаємось із відповіддю.</div><div class="step"><b>Точно ні</b> → реальна причина + коректне завершення.</div></div><div class="script">Тоді фіксую: <b>[домовленість]</b>. Наступний крок — <b>[дія]</b>, дедлайн — <b>[дата/час]</b>.</div>${btn('Завершити дзвінок','finish')}`,
finish:()=>`<span class="tag">Готово</span><h2>Дзвінок завершено</h2><div class="success">Зафіксуйте результат у CRM: короткий підсумок, домовленість, дедлайн і наступну задачу.</div><button class="primary" onclick="restart()">Почати новий дзвінок</button>`
};

function render(){breadcrumb.textContent=state.history.length?`Крок ${state.history.length+1} · ${state.current}`:'Старт';card.innerHTML=(screens[state.current]||screens.start)();backBtn.disabled=!state.history.length}
backBtn.addEventListener('click',back);restartBtn.addEventListener('click',restart);objectionBtn.addEventListener('click',()=>go('objections'));
window.go=go;window.restart=restart;render();
